### ISSUE TITLE
`AccountProvider` returns null in certain situations

### ISSUE THREAD

**Issue by ifiokjr** [StrataFoundation/strata#109]
It took me a while to understand why my app wasn't rendering, but this provider returns null when there is no active connection. I was wrapping the rest of the code.

https://github.com/StrataFoundation/strata/blob/3cead6b1dd2714a1b3fece42341adb5a78bee3fa/packages/react/src/contexts/accountContext.tsx#L33-L39

Would it be better if it returned the provider but with the cache undefined?

**Comment by ChewingGlass** [comment]
Agree, updating it to do this in the latest release. Don't have a commit link right now
