### ISSUE TITLE
[Bug] Different packages don't support tokens other than native

### ISSUE THREAD

**Issue by staccDOTsol** [StrataFoundation/strata#141]
Hey as discussed if someone tries loading a /profile/ url say, or other such things using a non-native token, the thing dies. it complains that some parent token is wrong. Altogether I thought I'd make an issue, even tho other stuff like /swap/ works fine - and this may be better on the wumbo repo, ha.

I'll get around to lookng at it in the soon-ish future (which depends entirely if COPE fine with a non-cope platform for the time being), but thought I'd drop this here - in case y'all wanna fix it first ;)

**Comment by ChewingGlass** [comment]
https://github.com/StrataFoundation/strata/pull/144

This should be fixed in the next release
