### ISSUE TITLE
Bonding curve will want to pay royalties to Hydra

### ISSUE THREAD

**Issue by staccDOTsol** [StrataFoundation/strata#149]
var ownerTokenRef = new PublicKey("H4oArQxf3U8hJ53DShAXo82678C5ck4NJRe4iB7iFc6p")
 let     buyTargetRoyalties = new PublicKey("95SUyc4q6kLLGqCS4tRzyy2eJ1awy53YdYXQRbBqAtQp")
     const {
          instructions: updateTokenBondingInstructions,
          signers: updateTokenBondingSigners,
        } =    await tokenCollectiveSdk.updateTokenBondingInstructions({
            tokenRef: ownerTokenRef,
            buyTargetRoyalties: buyTargetRoyalties,
              sellTargetRoyalties: buyTargetRoyalties,
            buyBaseRoyalties: buyTargetRoyalties,
            sellBaseRoyalties: buyTargetRoyalties,
                    })
        
        await tokenCollectiveSdk.sendInstructions(
          [...updateTokenBondingInstructions],
          [...updateTokenBondingSigners]
        )  

-->  {code: 3007, msg: 'The given account is owned by a different program than expected'}

--> use a regular wallet, not owned by hydra
--> works

https://solscan.io/tx/5Dqvh4tNQCXzmpSkjzFcfJetUg4YpzSNRSaq3gMLrPXayKLgAmKjux41W9S3aYvmkgT9LM5CM1FNsG2PVzB2T2da

**Comment by staccDOTsol** [comment]
I messed up that token something special

I've tried setting royalties back

var ownerTokenRef = new PublicKey("H4oArQxf3U8hJ53DShAXo82678C5ck4NJRe4iB7iFc6p")
let buyTargetRoyalties = new PublicKey("5sBpMQgTi7phxqRnErfbwx29vUsbUZoy1MLgY7aXuqeo")
const {
instructions: updateTokenBondingInstructions,
signers: updateTokenBondingSigners,
} = await tokenCollectiveSdk.updateTokenBondingInstructions({
tokenRef: ownerTokenRef,
buyTargetRoyalties: buyTargetRoyalties,
sellTargetRoyalties: buyTargetRoyalties,
buyBaseRoyalties: buyTargetRoyalties,
sellBaseRoyalties: buyTargetRoyalties,
})

    await tokenCollectiveSdk.sendInstructions(
      [...updateTokenBondingInstructions],
      [...updateTokenBondingSigners]
    )  


now https://fair3d.me if I try to trade into the tokens, I get

Program TBondmkCYxaPCKG4CHYfVTcwQ8on31xnJrPzk8F8WsS failed: invalid account data for instruction

https://solscan.io/tx/5k6H2ucsK2Nhdb56kShgAmUiaSBzPSFbWipgTBvxbxKoo3QKQJeMw2xDbhdexLWpgRQtXTinHKfCWdZesoBb3Mqj

**Comment by ChewingGlass** [comment]
@staccDOTsol those should be token accounts not wallets
