### ISSUE TITLE
Update solana token

### ISSUE THREAD

**Issue by easydeveloppement** [StrataFoundation/strata#315]
i'm trying to update a token name which was created with ex github token list.
the name displays properly on solscan's metadata tab, but everywhere else (phantom, solscan token page (token name), etc), the old name (which is still in token list) still appears.

Do anyone knows how to update this ?

**Comment by ChewingGlass** [comment]
Unfortunately, this is on everyone that is implementing the fallback. We've been in contact with the wallet providers and most are working on fixing this
