### ISSUE TITLE
MarketPlaceSDK createManualToken has a hard coded amount

### ISSUE THREAD

**Issue by LAV42** [StrataFoundation/strata#348]
https://github.com/StrataFoundation/strata/blob/7106d42db4f9521e2cd8eaa2cbad127ebdf8f4a2/packages/marketplace-sdk/src/index.ts#L393

**Comment by ThornM9** [comment]
Thanks for pointing this out, I just fixed this on master

**Comment by LAV42** [comment]
Thank you!
Would it be possible to have a minor release and publish the package on NPM @ThornM9 ?

**Comment by bryzettler** [comment]
@LAV42 version 3.10.3 of packages have been released with this change.
