### ISSUE TITLE
marketplace-ui errors

### ISSUE THREAD

**Issue by caramboleyo** [StrataFoundation/strata#368]
i tried to start the marketplace-ui but it tells me that the next config is invalid and that webpack fails on tons of typescript errors.

i also tried with `npm i --legacy-peer-deps` first and the yarn build but that also fails.

also yarn build from the root dir causes more than 1300 typescript errors.

The docs are not quite helpful also the api of strata itself is very unintuitive and i dont see any overall description explaining the concepts behind the api functions.

but you never come close to this anyway because you already fail in npm/yarn dependency hell.

maybe it because `npx lerna bootstrap` fails from the beginning?

**Comment by ChewingGlass** [comment]
This code is quite old by Solana standards. The code-rot from the amount that has changed over the last year may be too much to easily overcome. I would recommend finding something else to suit your needs and only use Strata as a reference implementation.

**Comment by caramboleyo** [comment]
i just tried to start it to get the ui from the launchpad running cause i dont understand how the protocol works and the docs are quite thin. For example i dont see a function anywhere to stop, delete or remove an offering.
